/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package submenus;

/**
 *
 * @author Alunos
 */
public class ProductMenu extends javax.swing.JFrame {

    /**
     * Creates new form ProductMenu
     */
    public ProductMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNewProduct = new javax.swing.JLabel();
        buttonNewProduct = new javax.swing.JButton();
        txtLocaleProduct = new javax.swing.JLabel();
        buttonLocaleProduct = new javax.swing.JButton();
        txtAllProducts = new javax.swing.JLabel();
        buttonAllProducts = new javax.swing.JButton();
        txtBestSellers = new javax.swing.JLabel();
        buttonBestSellers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        txtNewProduct.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNewProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNewProduct.setText("NOVO");
        txtNewProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNewProductMouseClicked(evt);
            }
        });

        buttonNewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newProduct.png"))); // NOI18N
        buttonNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewProductActionPerformed(evt);
            }
        });

        txtLocaleProduct.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtLocaleProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLocaleProduct.setText("LOCALIZAR");
        txtLocaleProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLocaleProductMouseClicked(evt);
            }
        });

        buttonLocaleProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/localeProduct.png"))); // NOI18N
        buttonLocaleProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLocaleProductActionPerformed(evt);
            }
        });

        txtAllProducts.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAllProducts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAllProducts.setText("TODOS");
        txtAllProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAllProductsMouseClicked(evt);
            }
        });

        buttonAllProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/allProducts.png"))); // NOI18N
        buttonAllProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllProductsActionPerformed(evt);
            }
        });

        txtBestSellers.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBestSellers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBestSellers.setText("MAIS VENDIDOS");
        txtBestSellers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBestSellersMouseClicked(evt);
            }
        });

        buttonBestSellers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/moreSale.png"))); // NOI18N
        buttonBestSellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBestSellersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLocaleProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLocaleProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAllProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAllProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBestSellers)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(buttonBestSellers, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAllProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAllProducts))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonBestSellers, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBestSellers))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonLocaleProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocaleProduct))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonNewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewProduct)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 527, 140);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewProductMouseClicked

    }//GEN-LAST:event_txtNewProductMouseClicked

    private void buttonNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewProductActionPerformed

    }//GEN-LAST:event_buttonNewProductActionPerformed

    private void txtLocaleProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLocaleProductMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocaleProductMouseClicked

    private void buttonLocaleProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLocaleProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLocaleProductActionPerformed

    private void txtAllProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAllProductsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllProductsMouseClicked

    private void buttonAllProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAllProductsActionPerformed

    private void txtBestSellersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBestSellersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBestSellersMouseClicked

    private void buttonBestSellersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBestSellersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBestSellersActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        this.dispose();
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAllProducts;
    private javax.swing.JButton buttonBestSellers;
    private javax.swing.JButton buttonLocaleProduct;
    private javax.swing.JButton buttonNewProduct;
    private javax.swing.JLabel txtAllProducts;
    private javax.swing.JLabel txtBestSellers;
    private javax.swing.JLabel txtLocaleProduct;
    private javax.swing.JLabel txtNewProduct;
    // End of variables declaration//GEN-END:variables
}
