/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package submenus;

/**
 *
 * @author Alunos
 */
public class ProviderMenu extends javax.swing.JFrame {

    /**
     * Creates new form StockMenu
     */
    public ProviderMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMissingItems = new javax.swing.JLabel();
        buttonMissingItems = new javax.swing.JButton();
        txtMissingItems1 = new javax.swing.JLabel();
        buttonMissingItems1 = new javax.swing.JButton();
        txtMissingItems2 = new javax.swing.JLabel();
        buttonMissingItems2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtMissingItems.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtMissingItems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMissingItems.setText("NOVO");
        txtMissingItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMissingItemsMouseClicked(evt);
            }
        });

        buttonMissingItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/faltStock.png"))); // NOI18N
        buttonMissingItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMissingItemsActionPerformed(evt);
            }
        });

        txtMissingItems1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtMissingItems1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMissingItems1.setText("LOCALIZAR");
        txtMissingItems1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMissingItems1MouseClicked(evt);
            }
        });

        buttonMissingItems1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/faltStock.png"))); // NOI18N
        buttonMissingItems1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMissingItems1ActionPerformed(evt);
            }
        });

        txtMissingItems2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtMissingItems2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMissingItems2.setText("TODOS");
        txtMissingItems2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMissingItems2MouseClicked(evt);
            }
        });

        buttonMissingItems2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/allProviders.png"))); // NOI18N
        buttonMissingItems2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMissingItems2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMissingItems, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMissingItems, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMissingItems1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMissingItems1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMissingItems2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMissingItems2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonMissingItems, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMissingItems))
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonMissingItems1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMissingItems1))
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonMissingItems2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMissingItems2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMissingItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMissingItemsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMissingItemsMouseClicked

    private void buttonMissingItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMissingItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMissingItemsActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        this.dispose();
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void txtMissingItems1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMissingItems1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMissingItems1MouseClicked

    private void buttonMissingItems1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMissingItems1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMissingItems1ActionPerformed

    private void txtMissingItems2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMissingItems2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMissingItems2MouseClicked

    private void buttonMissingItems2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMissingItems2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMissingItems2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProviderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProviderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProviderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProviderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProviderMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMissingItems;
    private javax.swing.JButton buttonMissingItems1;
    private javax.swing.JButton buttonMissingItems2;
    private javax.swing.JLabel txtMissingItems;
    private javax.swing.JLabel txtMissingItems1;
    private javax.swing.JLabel txtMissingItems2;
    // End of variables declaration//GEN-END:variables
}
