/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.findfiles;

import screen.allfiles.AllManual;
import callframes.CallOtherFrame;
import functioncontroller.LimitNumberCharacters;
import functioncontroller.UpperLetter;
import javax.swing.JFrame;
import screens.cadastrescreens.CadastreManual;
import setsoons.SetAndOrganizeSoons;

/**
 *
 * @author willi
 */
public class LocaleManual extends setsoons.AuxiliaryJFrame {

    /**
     * Creates new form LocaleManual
     */
    public LocaleManual() {
        initComponents();
        inputCodeDevice.setDocument(new LimitNumberCharacters());
        inputNameDevice.setDocument(new UpperLetter());
    }
    SetAndOrganizeSoons setAndOrganizeSoons = new SetAndOrganizeSoons();
    boolean inicializedWindow = false;
    private void callOtherScreen(JFrame screen){
        CallOtherFrame callOtherFrame = new CallOtherFrame();
        callOtherFrame.callOtherScreen(screen);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soonTavile = new javax.swing.JLabel();
        soonProxxi = new javax.swing.JLabel();
        txtFindManual = new javax.swing.JLabel();
        txtCodeDevice = new javax.swing.JLabel();
        txtNameDevice = new javax.swing.JLabel();
        buttonFindManual = new javax.swing.JButton();
        inputNameDevice = new javax.swing.JTextField();
        buttonAddManual = new javax.swing.JButton();
        inputCodeDevice = new javax.swing.JTextField();
        buttonAllManual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Localizar Manual");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtFindManual.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtFindManual.setText("Localizar Manuais");

        txtCodeDevice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCodeDevice.setText("Código do equipamento");

        txtNameDevice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNameDevice.setText("Nome do equipamento");

        buttonFindManual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        buttonFindManual.setText("Localizar");

        inputNameDevice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputNameDevice.setForeground(new java.awt.Color(51, 51, 51));
        inputNameDevice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputNameDeviceKeyPressed(evt);
            }
        });

        buttonAddManual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        buttonAddManual.setText("Adicionar");
        buttonAddManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddManualActionPerformed(evt);
            }
        });

        inputCodeDevice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        buttonAllManual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        buttonAllManual.setText("Todos");
        buttonAllManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllManualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(soonTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(soonProxxi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodeDevice)
                            .addComponent(txtNameDevice))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNameDevice)
                            .addComponent(inputCodeDevice)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonFindManual)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAllManual)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAddManual)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFindManual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soonTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soonProxxi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFindManual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodeDevice)
                    .addComponent(inputCodeDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameDevice)
                    .addComponent(inputNameDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFindManual)
                    .addComponent(buttonAddManual)
                    .addComponent(buttonAllManual))
                .addGap(32, 32, 32))
        );

        setSize(new java.awt.Dimension(508, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameDeviceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNameDeviceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameDeviceKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(inicializedWindow==false){
            inicializedWindow = true;
            setAndOrganizeSoons.SetSoons(this);
            setAndOrganizeSoons.SetLocationSoons(this, soonTavile.getX(), soonTavile.getY(), soonProxxi.getX(), soonProxxi.getY());
        }
    }//GEN-LAST:event_formWindowActivated

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        setAndOrganizeSoons.SetLocationSoons(this, soonTavile.getX(), soonTavile.getY(), soonProxxi.getX(), soonProxxi.getY());
    }//GEN-LAST:event_formComponentResized

    private void buttonAddManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddManualActionPerformed
        CadastreManual cadastreManual = new CadastreManual();
        this.dispose();
        callOtherScreen(cadastreManual);
    }//GEN-LAST:event_buttonAddManualActionPerformed

    private void buttonAllManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllManualActionPerformed
        AllManual allManual = new AllManual();
        this.dispose();
        callOtherScreen(allManual);
    }//GEN-LAST:event_buttonAllManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocaleManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocaleManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocaleManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocaleManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocaleManual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddManual;
    private javax.swing.JButton buttonAllManual;
    private javax.swing.JButton buttonFindManual;
    private javax.swing.JTextField inputCodeDevice;
    private javax.swing.JTextField inputNameDevice;
    public static javax.swing.JLabel soonProxxi;
    public static javax.swing.JLabel soonTavile;
    private javax.swing.JLabel txtCodeDevice;
    private javax.swing.JLabel txtFindManual;
    private javax.swing.JLabel txtNameDevice;
    // End of variables declaration//GEN-END:variables
}
