package screens.cadastrescreens;
import callframes.CallOtherFrame;
import functioncontroller.GetDateSystem;
import functioncontroller.LimitNumberCharacters;
import functioncontroller.UpperLetter;
import functionsuport.CallOSScreen;
import functionsuport.DisableInputsOSEditOS;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import screens.files.editfiles.OSEditOS;
import setsoons.SetAndOrganizeSoons;

/**
 *
 * @author willi
 */
public class CadastreOS extends setsoons.AuxiliaryJFrame {

    /**
     * Creates new form CadastreOS
     */
    public CadastreOS(){
        initComponents();
        inputSerialDevice.setDocument(new LimitNumberCharacters());
        inputCodeDevice.setDocument(new LimitNumberCharacters());
        inputNameDevice.setDocument(new UpperLetter());
        inputObservations.setLineWrap(true);
        inputObservations.setWrapStyleWord(true);
        inputObservations.setDocument(new UpperLetter());
    }
    SetAndOrganizeSoons setAndOrganizeSoons = new SetAndOrganizeSoons();
    boolean inicializedWindow = false;
    private void callOtherScreen(JFrame screen){
        CallOtherFrame callOtherFrame = new CallOtherFrame();
        callOtherFrame.callOtherScreen(screen);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soonTavile = new javax.swing.JLabel();
        soonProxxi = new javax.swing.JLabel();
        txtNameOfDevice = new javax.swing.JLabel();
        inputCodeDevice = new javax.swing.JTextField();
        buttonCadastre = new javax.swing.JButton();
        inputBranchTavile = new javax.swing.JComboBox<>();
        inputNameDevice = new javax.swing.JTextField();
        inputDateOfOpening = new javax.swing.JFormattedTextField();
        txtNewEquipament = new javax.swing.JLabel();
        txtSerialOfDevice = new javax.swing.JLabel();
        txtBranchTavile = new javax.swing.JLabel();
        txtOpeningDate = new javax.swing.JLabel();
        txtCodeOfDevice = new javax.swing.JLabel();
        inputObservation = new javax.swing.JScrollPane();
        inputObservations = new javax.swing.JTextArea();
        txtObservation = new javax.swing.JLabel();
        txtSituationDevice = new javax.swing.JLabel();
        inputSituationDevice = new javax.swing.JComboBox<>();
        inputSerialDevice = new javax.swing.JTextField();
        buttonOpenOS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Equipamento");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtNameOfDevice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNameOfDevice.setText("Nome do equipamento");

        inputCodeDevice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputCodeDevice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputCodeDeviceKeyPressed(evt);
            }
        });

        buttonCadastre.setText("CADASTRAR");
        buttonCadastre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastreActionPerformed(evt);
            }
        });

        inputBranchTavile.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputBranchTavile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        inputNameDevice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        try {
            inputDateOfOpening.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputDateOfOpening.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputDateOfOpening.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputDateOfOpeningFocusGained(evt);
            }
        });

        txtNewEquipament.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtNewEquipament.setText("Cadastrar Equipamento");

        txtSerialOfDevice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSerialOfDevice.setText("Serial");

        txtBranchTavile.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBranchTavile.setText("Filial");
        txtBranchTavile.setToolTipText("");

        txtOpeningDate.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtOpeningDate.setText("Data de abertura");

        txtCodeOfDevice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCodeOfDevice.setText("Código do equipamento");

        inputObservations.setColumns(20);
        inputObservations.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputObservations.setRows(5);
        inputObservation.setViewportView(inputObservations);

        txtObservation.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtObservation.setText("Observações");

        txtSituationDevice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSituationDevice.setText("Situação");
        txtSituationDevice.setToolTipText("");

        inputSituationDevice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputSituationDevice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        inputSerialDevice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputSerialDevice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputSerialDeviceKeyPressed(evt);
            }
        });

        buttonOpenOS.setText("ABRIR OS");
        buttonOpenOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(soonTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(soonProxxi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNewEquipament)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtObservation, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCadastre)
                        .addGap(33, 33, 33)
                        .addComponent(buttonOpenOS))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(inputObservation, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBranchTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(inputBranchTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(txtSituationDevice)
                                .addGap(48, 48, 48)
                                .addComponent(inputSituationDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNameOfDevice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputNameDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(txtOpeningDate)
                                .addGap(39, 39, 39)
                                .addComponent(inputDateOfOpening, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSerialOfDevice)
                        .addGap(38, 38, 38)
                        .addComponent(inputSerialDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txtCodeOfDevice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputCodeDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soonTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soonProxxi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(txtNewEquipament)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialOfDevice)
                    .addComponent(txtCodeOfDevice)
                    .addComponent(inputCodeDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSerialDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameOfDevice)
                    .addComponent(inputNameDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOpeningDate)
                    .addComponent(inputDateOfOpening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSituationDevice)
                        .addComponent(inputSituationDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBranchTavile))
                    .addComponent(inputBranchTavile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(txtObservation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputObservation, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadastre)
                    .addComponent(buttonOpenOS))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(876, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(inicializedWindow==false){
            inicializedWindow = true;
            setAndOrganizeSoons.SetSoons(this);
            setAndOrganizeSoons.SetLocationSoons(this, soonTavile.getX(), soonTavile.getY(), soonProxxi.getX(), soonProxxi.getY());
            GetDateSystem getDateSystem = new GetDateSystem();
            inputDateOfOpening.setText(getDateSystem.dateOfSystem());
        }
    }//GEN-LAST:event_formWindowActivated

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        setAndOrganizeSoons.SetLocationSoons(this, soonTavile.getX(), soonTavile.getY(), soonProxxi.getX(), soonProxxi.getY());
    }//GEN-LAST:event_formComponentResized

    private void inputCodeDeviceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCodeDeviceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodeDeviceKeyPressed

    private void buttonCadastreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastreActionPerformed
            JOptionPane.showMessageDialog(null, "ITEM CADASTRADO COM SUCESSO");
            DisableInputsOSEditOS disableInputsOSEditOS = new DisableInputsOSEditOS();
            //disableInputsOSEditOS.disableInputs();
            this.dispose();
            CallOSScreen callOSScreen = new CallOSScreen();
            callOSScreen.callScreen();
    }//GEN-LAST:event_buttonCadastreActionPerformed

    private void inputDateOfOpeningFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputDateOfOpeningFocusGained
        inputDateOfOpening.selectAll();
    }//GEN-LAST:event_inputDateOfOpeningFocusGained

    private void inputSerialDeviceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSerialDeviceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSerialDeviceKeyPressed

    private void buttonOpenOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenOSActionPerformed
        JOptionPane.showMessageDialog(null, "OS ABERTA COM SUCESSO NO SISTEMA!");
    }//GEN-LAST:event_buttonOpenOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastreOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastreOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastreOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastreOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastreOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastre;
    private javax.swing.JButton buttonOpenOS;
    private javax.swing.JComboBox<String> inputBranchTavile;
    private javax.swing.JTextField inputCodeDevice;
    private javax.swing.JFormattedTextField inputDateOfOpening;
    private javax.swing.JTextField inputNameDevice;
    private javax.swing.JScrollPane inputObservation;
    private javax.swing.JTextArea inputObservations;
    private javax.swing.JTextField inputSerialDevice;
    private javax.swing.JComboBox<String> inputSituationDevice;
    public static javax.swing.JLabel soonProxxi;
    public static javax.swing.JLabel soonTavile;
    private javax.swing.JLabel txtBranchTavile;
    private javax.swing.JLabel txtCodeOfDevice;
    private javax.swing.JLabel txtNameOfDevice;
    private javax.swing.JLabel txtNewEquipament;
    private javax.swing.JLabel txtObservation;
    private javax.swing.JLabel txtOpeningDate;
    private javax.swing.JLabel txtSerialOfDevice;
    private javax.swing.JLabel txtSituationDevice;
    // End of variables declaration//GEN-END:variables
}
