package screens.cadastrescreens;
import functioncontroller.LimitNumberCharacters;
import functioncontroller.UpperLetter;
import functionsuport.CallItemScreen;
import javax.swing.JOptionPane;
import setsoons.SetAndOrganizeSoons;

/**
 *
 * @author willi
 */
public class CadastreItemStock extends setsoons.AuxiliaryJFrame {

    /**
     * Creates new form CadastreItemStock
     */
    public CadastreItemStock() {
        initComponents();
        inputCodeItem.setDocument(new LimitNumberCharacters());
        inputNameItem.setDocument(new UpperLetter());
        inputAddressItem.setDocument(new UpperLetter());
    }
    SetAndOrganizeSoons setAndOrganizeSoons = new SetAndOrganizeSoons();
    boolean inicializedWindow = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        soonTavile = new javax.swing.JLabel();
        soonProxxi = new javax.swing.JLabel();
        txtNewItemInStock = new javax.swing.JLabel();
        txtCodeOfItem = new javax.swing.JLabel();
        inputCodeItem = new javax.swing.JTextField();
        txtNameOfItem = new javax.swing.JLabel();
        inputNameItem = new javax.swing.JTextField();
        txtQuantityRequested = new javax.swing.JLabel();
        inputQuantityRequested = new javax.swing.JSpinner();
        txaddressItem = new javax.swing.JLabel();
        inputAddressItem = new javax.swing.JTextField();
        buttonAddItem = new javax.swing.JButton();
        tableOfStock = new javax.swing.JScrollPane();
        tablePartsOfStock = new javax.swing.JTable();
        buttonSave = new javax.swing.JButton();
        checkFavoriteItem = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Item ao seu Saldo");
        setSize(new java.awt.Dimension(553, 504));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtNewItemInStock.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtNewItemInStock.setText("Adicionar peças ao seu estoque");

        txtCodeOfItem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCodeOfItem.setText("Código da peça");

        inputCodeItem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputCodeItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputCodeItemKeyPressed(evt);
            }
        });

        txtNameOfItem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNameOfItem.setText("Nome da peça");

        inputNameItem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtQuantityRequested.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtQuantityRequested.setText("Quantidade");

        inputQuantityRequested.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputQuantityRequested.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        txaddressItem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txaddressItem.setText("Endereço");

        inputAddressItem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputAddressItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputAddressItemKeyPressed(evt);
            }
        });

        buttonAddItem.setText("ADICIONAR");

        tablePartsOfStock.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tablePartsOfStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código do Produto", "Descrição", "Quantidade"
            }
        ));
        tableOfStock.setViewportView(tablePartsOfStock);

        buttonSave.setText("SALVAR");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        checkFavoriteItem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        checkFavoriteItem.setText("Peça Favorita");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(soonTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(soonProxxi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSave)
                    .addComponent(tableOfStock, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txaddressItem)
                            .addComponent(txtQuantityRequested, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameOfItem)
                            .addComponent(txtCodeOfItem)
                            .addComponent(checkFavoriteItem))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAddItem)
                            .addComponent(inputQuantityRequested, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAddressItem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputCodeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNewItemInStock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soonTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soonProxxi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewItemInStock)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodeOfItem)
                    .addComponent(inputCodeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameOfItem)
                    .addComponent(inputNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantityRequested)
                    .addComponent(inputQuantityRequested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txaddressItem)
                    .addComponent(inputAddressItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddItem)
                    .addComponent(checkFavoriteItem))
                .addGap(18, 18, 18)
                .addComponent(tableOfStock, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSave)
                .addGap(20, 20, 20))
        );

        setSize(new java.awt.Dimension(569, 543));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputCodeItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCodeItemKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodeItemKeyPressed

    private void inputAddressItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAddressItemKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAddressItemKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(inicializedWindow==false){
            inicializedWindow = true;
            setAndOrganizeSoons.SetSoons(this);
            setAndOrganizeSoons.SetLocationSoons(this, soonTavile.getX(), soonTavile.getY(), soonProxxi.getX(), soonProxxi.getY());
        }
    }//GEN-LAST:event_formWindowActivated

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        setAndOrganizeSoons.SetLocationSoons(this, soonTavile.getX(), soonTavile.getY(), soonProxxi.getX(), soonProxxi.getY());
    }//GEN-LAST:event_formComponentResized

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        CallItemScreen callOrderScreen = new CallItemScreen();
        JOptionPane.showMessageDialog(null, "ITEM CADASTRADO COM SUCESSO");
        this.dispose();
        callOrderScreen.callScreen();
    }//GEN-LAST:event_buttonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastreItemStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastreItemStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastreItemStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastreItemStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastreItemStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSave;
    private javax.swing.JCheckBox checkFavoriteItem;
    private javax.swing.JTextField inputAddressItem;
    private javax.swing.JTextField inputCodeItem;
    private javax.swing.JTextField inputNameItem;
    private javax.swing.JSpinner inputQuantityRequested;
    public static javax.swing.JLabel soonProxxi;
    public static javax.swing.JLabel soonTavile;
    private javax.swing.JScrollPane tableOfStock;
    private javax.swing.JTable tablePartsOfStock;
    private javax.swing.JLabel txaddressItem;
    private javax.swing.JLabel txtCodeOfItem;
    private javax.swing.JLabel txtNameOfItem;
    private javax.swing.JLabel txtNewItemInStock;
    private javax.swing.JLabel txtQuantityRequested;
    // End of variables declaration//GEN-END:variables
}
