package screens.cadastrescreens;
import callframes.CallOtherFrame;
import functioncontroller.LimitNumberCharacters;
import functionsuport.CallOrderScreen;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import setsoons.SetAndOrganizeSoons;

/**
 *
 * @author willi
 */
public class CadastreOrder extends setsoons.AuxiliaryJFrame {

    /**
     * Creates new form CadastreOrder
     */
    public CadastreOrder() {
        initComponents();
        inputCodePart.setDocument(new LimitNumberCharacters());
    }
    SetAndOrganizeSoons setAndOrganizeSoons = new SetAndOrganizeSoons();
    boolean inicializedWindow = false;
    private void callOtherScreen(JFrame screen){
        CallOtherFrame callOtherFrame = new CallOtherFrame();
        callOtherFrame.callOtherScreen(screen);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soonTavile = new javax.swing.JLabel();
        soonProxxi = new javax.swing.JLabel();
        txtRequestingBranch = new javax.swing.JLabel();
        txtSupplierBranch = new javax.swing.JLabel();
        inputRequestingBranch = new javax.swing.JComboBox<>();
        inputSupplierBranch = new javax.swing.JComboBox<>();
        txtCodePart = new javax.swing.JLabel();
        txtQuantityRequested = new javax.swing.JLabel();
        tableOfOrders = new javax.swing.JScrollPane();
        tablePartsOfOrder = new javax.swing.JTable();
        inputCodePart = new javax.swing.JTextField();
        buttonAddNewOrder = new javax.swing.JButton();
        buttonSaveOrder = new javax.swing.JButton();
        txtNewOrder = new javax.swing.JLabel();
        inputQuantityRequested = new javax.swing.JSpinner();
        buttonRemoverOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Pedido");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtRequestingBranch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRequestingBranch.setText("Filial Solicitante");

        txtSupplierBranch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSupplierBranch.setText("Filial Fornecedora");

        inputRequestingBranch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputRequestingBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        inputSupplierBranch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputSupplierBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtCodePart.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCodePart.setText("Código da peça");

        txtQuantityRequested.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtQuantityRequested.setText("Quantidade solicitada");

        tablePartsOfOrder.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tablePartsOfOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código do Produto", "Descrição", "Quantidade"
            }
        ));
        tableOfOrders.setViewportView(tablePartsOfOrder);

        inputCodePart.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputCodePart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputCodePartKeyPressed(evt);
            }
        });

        buttonAddNewOrder.setText("ADICIONAR");

        buttonSaveOrder.setText("SALVAR");
        buttonSaveOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveOrderActionPerformed(evt);
            }
        });

        txtNewOrder.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtNewOrder.setText("Novo Pedido");

        inputQuantityRequested.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputQuantityRequested.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        buttonRemoverOrder.setText("REMOVER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(soonTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(soonProxxi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNewOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableOfOrders)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRequestingBranch)
                            .addComponent(txtCodePart))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputCodePart, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addGap(68, 68, 68))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputRequestingBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQuantityRequested, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputQuantityRequested, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtSupplierBranch)
                                .addGap(29, 29, 29)
                                .addComponent(inputSupplierBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSaveOrder)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonAddNewOrder)
                                .addGap(36, 36, 36)
                                .addComponent(buttonRemoverOrder)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soonTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soonProxxi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(txtNewOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSupplierBranch)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRequestingBranch)
                        .addComponent(inputRequestingBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputSupplierBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodePart)
                    .addComponent(inputCodePart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantityRequested)
                    .addComponent(inputQuantityRequested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddNewOrder)
                    .addComponent(buttonRemoverOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(tableOfOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonSaveOrder)
                .addGap(36, 36, 36))
        );

        setSize(new java.awt.Dimension(914, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(inicializedWindow==false){
            inicializedWindow = true;
            setAndOrganizeSoons.SetSoons(this);
            setAndOrganizeSoons.SetLocationSoons(this, soonTavile.getX(), soonTavile.getY(), soonProxxi.getX(), soonProxxi.getY());
        }
    }//GEN-LAST:event_formWindowActivated

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        setAndOrganizeSoons.SetLocationSoons(this, soonTavile.getX(), soonTavile.getY(), soonProxxi.getX(), soonProxxi.getY());
    }//GEN-LAST:event_formComponentResized

    private void inputCodePartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCodePartKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodePartKeyPressed

    private void buttonSaveOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveOrderActionPerformed
        JOptionPane.showMessageDialog(null, "PEDIDO CADASTRADO COM SUCESSO");
        CallOrderScreen callOrderScreen = new CallOrderScreen();
        this.dispose();
        callOrderScreen.callScreen();
    }//GEN-LAST:event_buttonSaveOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastreOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastreOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastreOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastreOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastreOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddNewOrder;
    private javax.swing.JButton buttonRemoverOrder;
    private javax.swing.JButton buttonSaveOrder;
    private javax.swing.JTextField inputCodePart;
    private javax.swing.JSpinner inputQuantityRequested;
    private javax.swing.JComboBox<String> inputRequestingBranch;
    private javax.swing.JComboBox<String> inputSupplierBranch;
    public static javax.swing.JLabel soonProxxi;
    public static javax.swing.JLabel soonTavile;
    private javax.swing.JScrollPane tableOfOrders;
    private javax.swing.JTable tablePartsOfOrder;
    private javax.swing.JLabel txtCodePart;
    private javax.swing.JLabel txtNewOrder;
    private javax.swing.JLabel txtQuantityRequested;
    private javax.swing.JLabel txtRequestingBranch;
    private javax.swing.JLabel txtSupplierBranch;
    // End of variables declaration//GEN-END:variables
}
