/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author Alunos
 */
public class AllBills extends javax.swing.JFrame {
    int x = 0;
    /**
     * Creates new form AllBills
     */
    public AllBills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAllBills = new javax.swing.JLabel();
        tableAllBills = new javax.swing.JScrollPane();
        tableBills = new javax.swing.JTable();
        inputIdentification = new javax.swing.JTextField();
        buttonShow = new javax.swing.JButton();
        buttonPrinter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Todas as Contas");
        setResizable(false);
        getContentPane().setLayout(null);

        txtAllBills.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtAllBills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAllBills.setText("TODOS AS CONTAS");
        getContentPane().add(txtAllBills);
        txtAllBills.setBounds(190, 10, 300, 32);

        tableBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número da Conta", "CPF / CNPJ Pagador", "Descrição Pagador", "CPF / CNPJ Recebedor", "Descrição Recebedor", "Valor"
            }
        ));
        tableAllBills.setViewportView(tableBills);

        getContentPane().add(tableAllBills);
        tableAllBills.setBounds(20, 110, 620, 320);

        inputIdentification.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        inputIdentification.setText("CPF / CNPJ");
        inputIdentification.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputIdentificationFocusGained(evt);
            }
        });
        inputIdentification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputIdentificationKeyTyped(evt);
            }
        });
        getContentPane().add(inputIdentification);
        inputIdentification.setBounds(20, 60, 190, 30);

        buttonShow.setText("MOSTRAR");
        buttonShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowActionPerformed(evt);
            }
        });
        getContentPane().add(buttonShow);
        buttonShow.setBounds(240, 60, 90, 30);

        buttonPrinter.setText("IMPRIMIR");
        getContentPane().add(buttonPrinter);
        buttonPrinter.setBounds(360, 60, 90, 32);

        setSize(new java.awt.Dimension(664, 474));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputIdentificationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputIdentificationFocusGained
        inputIdentification.selectAll();
    }//GEN-LAST:event_inputIdentificationFocusGained

    private void inputIdentificationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputIdentificationKeyTyped
        if(inputIdentification.getText().equals("")){
            inputIdentification.setText("CPF / CNPJ");
            x=0;
        }
        else if(x==0){
            x++;
            inputIdentification.setText("");
        }
    }//GEN-LAST:event_inputIdentificationKeyTyped

    private void buttonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowActionPerformed
        BillScreen billScreen = new BillScreen();
        billScreen.setVisible(true);
    }//GEN-LAST:event_buttonShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllBills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPrinter;
    private javax.swing.JButton buttonShow;
    private javax.swing.JTextField inputIdentification;
    private javax.swing.JScrollPane tableAllBills;
    private javax.swing.JTable tableBills;
    public static javax.swing.JLabel txtAllBills;
    // End of variables declaration//GEN-END:variables
}
