/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import functioncontroller.ScreenUserSize;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class ImageScreen extends javax.swing.JFrame {
    int x = 0;
    public String adress = null;
    public NewClient newClient;
    public ClientScreen clientScreen;
    public NewProduct newProduct;
    public ProductScreen productScreen;
    public NewEmployee newEmployee;
    public EmployeeScreen employeeScreen;
    public boolean itsANewClient = false;
    public boolean itsANewProduct = false;
    public boolean itsANewEmployee = false;
    /**
     * Creates new form ProductImage
     */
    public ImageScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPrinter = new javax.swing.JButton();
        outputPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Imagem");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        buttonPrinter.setText("IMPRIMIR");
        buttonPrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrinterActionPerformed(evt);
            }
        });

        outputPicture.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        outputPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputPicture.setText("SEM IMAGEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(buttonPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPrinter)
                .addContainerGap())
        );

        setBounds(0, 0, 559, 468);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(x==0){
            x++;
            ScreenUserSize screenUserSize = new ScreenUserSize();
            String[] size = screenUserSize.sizeOfScreen().split(";");
            this.setSize(Integer.parseInt(size[0]), Integer.parseInt(size[1]));
            if(!adress.equals(null)){
                outputPicture.setText("");
            }
            ImageIcon imagen = new ImageIcon(adress);
            outputPicture.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(outputPicture.getWidth(), outputPicture.getHeight(), Image.SCALE_DEFAULT)));
        }
    }//GEN-LAST:event_formWindowActivated

    private void buttonPrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrinterActionPerformed
        if(buttonPrinter.getText().equals("EXCLUIR")){
            if(newClient!=null){
                if(itsANewClient==true){
                    newClient.imageAdress = null;
                    newClient.buttonPhoto.setIcon(null);
                    newClient.buttonPhoto.setText("FOTO");
                }
                else{
                    clientScreen.imageAdress = null;
                    clientScreen.buttonPhoto.setIcon(null);
                    clientScreen.buttonPhoto.setText("FOTO");
                }
            }
            else if(newProduct!=null){
                if(itsANewClient==true){
                    newProduct.imageAdress = null;
                    newProduct.inputPhoto.setIcon(null);
                    newProduct.inputPhoto.setText("FOTO");
                }
                else{
                    productScreen.imageAdress = null;
                    productScreen.outputPhoto.setIcon(null);
                    productScreen.outputPhoto.setText("FOTO");
                }
            }
            File file = new File(adress);
            file.delete();
            JOptionPane.showMessageDialog(null, "FOTO APAGADA");
            this.dispose();
        }
    }//GEN-LAST:event_buttonPrinterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton buttonPrinter;
    public javax.swing.JLabel outputPicture;
    // End of variables declaration//GEN-END:variables
}
