package screens;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import connectionbd.ConnectionModule;
import functioncontroller.UpperLetter;
import javax.swing.JOptionPane;


public class LocaleProduct extends javax.swing.JFrame {
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public LocaleProduct() {
        initComponents();
        ConnectionModule connect = new ConnectionModule();
        connection = connect.getConnectionMySQL();
        inputProductCode.setDocument(new UpperLetter());
    }
    private void setProduct(){
        String sql ="select barCode from product where barCode=?";
        try {
            pst=connection.prepareStatement(sql);
            pst.setString(1, inputProductCode.getText());
            rs= pst.executeQuery();
            if(rs.next()){
                ProductScreen productScreen = new ProductScreen();
                productScreen.setTitle("Produto: " + rs.getString(1));
                this.dispose();
                productScreen.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "PRODUTO NÃO LOCALIZADO NO SISTEMA");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLocaleProduct = new javax.swing.JLabel();
        txtCodeProduct = new javax.swing.JLabel();
        inputProductCode = new javax.swing.JTextField();
        buttonLocale = new javax.swing.JButton();
        buttonAllProducts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Localizar Produtos");
        setResizable(false);
        getContentPane().setLayout(null);

        txtLocaleProduct.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtLocaleProduct.setText("LOCALIZAR PRODUTOS");
        getContentPane().add(txtLocaleProduct);
        txtLocaleProduct.setBounds(50, 20, 290, 32);

        txtCodeProduct.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCodeProduct.setText("Código do Produto");
        getContentPane().add(txtCodeProduct);
        txtCodeProduct.setBounds(20, 70, 150, 20);
        getContentPane().add(inputProductCode);
        inputProductCode.setBounds(20, 100, 240, 25);

        buttonLocale.setText("LOCALIZAR");
        buttonLocale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLocaleActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLocale);
        buttonLocale.setBounds(20, 150, 110, 23);

        buttonAllProducts.setText("TODOS OS PRODUTOS");
        buttonAllProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllProductsActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAllProducts);
        buttonAllProducts.setBounds(160, 150, 170, 23);

        setSize(new java.awt.Dimension(400, 226));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLocaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLocaleActionPerformed
        setProduct();
    }//GEN-LAST:event_buttonLocaleActionPerformed

    private void buttonAllProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllProductsActionPerformed
        AllProducts allProducts = new AllProducts();
        this.dispose();
        allProducts.setVisible(true);
    }//GEN-LAST:event_buttonAllProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocaleProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocaleProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocaleProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocaleProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocaleProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAllProducts;
    private javax.swing.JButton buttonLocale;
    private javax.swing.JTextField inputProductCode;
    private javax.swing.JLabel txtCodeProduct;
    private javax.swing.JLabel txtLocaleProduct;
    // End of variables declaration//GEN-END:variables
}
