/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author Alunos
 */
public class LocaleBill extends javax.swing.JFrame {

    /**
     * Creates new form LocaleBill
     */
    public LocaleBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLocaleBill = new javax.swing.JLabel();
        txtBillCode = new javax.swing.JLabel();
        inputBillCode = new javax.swing.JTextField();
        buttonLocale = new javax.swing.JButton();
        buttonAllBills = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Localizar Conta");
        setResizable(false);
        getContentPane().setLayout(null);

        txtLocaleBill.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtLocaleBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLocaleBill.setText("LOCALIZAR CONTA");
        getContentPane().add(txtLocaleBill);
        txtLocaleBill.setBounds(20, 10, 280, 30);

        txtBillCode.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtBillCode.setText("Código da Conta");
        getContentPane().add(txtBillCode);
        txtBillCode.setBounds(20, 60, 130, 20);

        inputBillCode.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputBillCode);
        inputBillCode.setBounds(20, 90, 240, 24);

        buttonLocale.setText("LOCALIZAR");
        buttonLocale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLocaleActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLocale);
        buttonLocale.setBounds(20, 130, 110, 32);

        buttonAllBills.setText("TODAS AS CONTAS");
        buttonAllBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllBillsActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAllBills);
        buttonAllBills.setBounds(150, 130, 160, 32);

        setSize(new java.awt.Dimension(329, 208));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLocaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLocaleActionPerformed
        BillScreen billScreen = new BillScreen();
        this.dispose();
        billScreen.setVisible(true);
    }//GEN-LAST:event_buttonLocaleActionPerformed

    private void buttonAllBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllBillsActionPerformed
        AllBills allBills = new AllBills();
        this.dispose();
        allBills.setVisible(true);
    }//GEN-LAST:event_buttonAllBillsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocaleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocaleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocaleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocaleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocaleBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAllBills;
    private javax.swing.JButton buttonLocale;
    private javax.swing.JTextField inputBillCode;
    private javax.swing.JLabel txtBillCode;
    private javax.swing.JLabel txtLocaleBill;
    // End of variables declaration//GEN-END:variables
}
