/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author Alunos
 */
public class LocaleEmployee extends javax.swing.JFrame {
    int x = 0;
    /**
     * Creates new form LocaleScreen
     */
    public LocaleEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLocaleEmployee = new javax.swing.JLabel();
        inputNameEmployee = new javax.swing.JTextField();
        tableLocaleEmplyees = new javax.swing.JScrollPane();
        tableEmployees = new javax.swing.JTable();
        buttonShowClient = new javax.swing.JButton();
        inputCPFEmployee = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Localizar Funcionário");
        setResizable(false);
        getContentPane().setLayout(null);

        txtLocaleEmployee.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtLocaleEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLocaleEmployee.setText("LOCALIZAR FUNCIONÁRIO");
        getContentPane().add(txtLocaleEmployee);
        txtLocaleEmployee.setBounds(180, 20, 340, 32);

        inputNameEmployee.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        inputNameEmployee.setText("NOME DO FUNCIONÁRIO");
        inputNameEmployee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNameEmployeeFocusGained(evt);
            }
        });
        inputNameEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputNameEmployeeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNameEmployeeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNameEmployeeKeyTyped(evt);
            }
        });
        getContentPane().add(inputNameEmployee);
        inputNameEmployee.setBounds(290, 70, 256, 30);

        tableEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Email", "Telefone", "Celular"
            }
        ));
        tableLocaleEmplyees.setViewportView(tableEmployees);

        getContentPane().add(tableLocaleEmplyees);
        tableLocaleEmplyees.setBounds(10, 120, 690, 290);

        buttonShowClient.setText("MOSTRAR");
        buttonShowClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowClientActionPerformed(evt);
            }
        });
        getContentPane().add(buttonShowClient);
        buttonShowClient.setBounds(570, 70, 90, 30);

        inputCPFEmployee.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        inputCPFEmployee.setText("CPF DO FUNCIONÁRIO");
        inputCPFEmployee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputCPFEmployeeFocusGained(evt);
            }
        });
        inputCPFEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputCPFEmployeeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputCPFEmployeeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputCPFEmployeeKeyTyped(evt);
            }
        });
        getContentPane().add(inputCPFEmployee);
        inputCPFEmployee.setBounds(10, 70, 256, 30);

        setSize(new java.awt.Dimension(724, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameEmployeeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNameEmployeeFocusGained
        inputNameEmployee.selectAll();
    }//GEN-LAST:event_inputNameEmployeeFocusGained

    private void inputNameEmployeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNameEmployeeKeyPressed

    }//GEN-LAST:event_inputNameEmployeeKeyPressed

    private void inputNameEmployeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNameEmployeeKeyReleased

    }//GEN-LAST:event_inputNameEmployeeKeyReleased

    private void inputNameEmployeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNameEmployeeKeyTyped
        if(inputNameEmployee.getText().equals("")){
            inputNameEmployee.setText("NOME DO FUNCIONÁRIO");
            x=0;
        }
        else if(x==0){
            x++;
            inputNameEmployee.setText("");
        }
    }//GEN-LAST:event_inputNameEmployeeKeyTyped

    private void buttonShowClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowClientActionPerformed
        EmployeeScreen employeeScreen = new EmployeeScreen();
        employeeScreen.setVisible(true);
    }//GEN-LAST:event_buttonShowClientActionPerformed

    private void inputCPFEmployeeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCPFEmployeeFocusGained
        inputCPFEmployee.selectAll();
    }//GEN-LAST:event_inputCPFEmployeeFocusGained

    private void inputCPFEmployeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCPFEmployeeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCPFEmployeeKeyPressed

    private void inputCPFEmployeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCPFEmployeeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCPFEmployeeKeyReleased

    private void inputCPFEmployeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCPFEmployeeKeyTyped
        if(inputCPFEmployee.getText().equals("")){
            inputCPFEmployee.setText("CPF DO FUNCIONÁRIO");
            x=0;
        }
        else if(x==0){
            x++;
            inputCPFEmployee.setText("");
        }
    }//GEN-LAST:event_inputCPFEmployeeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocaleEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocaleEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocaleEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocaleEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocaleEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonShowClient;
    private javax.swing.JTextField inputCPFEmployee;
    private javax.swing.JTextField inputNameEmployee;
    private javax.swing.JTable tableEmployees;
    private javax.swing.JScrollPane tableLocaleEmplyees;
    private javax.swing.JLabel txtLocaleEmployee;
    // End of variables declaration//GEN-END:variables
}
