package screens;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import connectionbd.ConnectionModule;
import formattingmask.MaskCPFAndCNPJ;
import javax.swing.JOptionPane;
public class LocaleProvider extends javax.swing.JFrame {
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form LocaleProvider
     */
    public LocaleProvider() {
        initComponents();
        ConnectionModule connect = new ConnectionModule();
        connection = connect.getConnectionMySQL();
        inputCPFOrCNPJ.setDocument(new MaskCPFAndCNPJ());
    }
    private void setProvider(){
        String sql ="select codeProvider from provider where cpf=?";
        try {
            pst=connection.prepareStatement(sql);
            pst.setString(1, inputCPFOrCNPJ.getText());
            rs= pst.executeQuery();
            if(rs.next()){
                ProviderScreen providerScreen = new ProviderScreen();
                providerScreen.setTitle("Fornecedor: " + rs.getString(1));
                this.dispose();
                providerScreen.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "FORNECEDOR NÃO LOCALIZADO NO SISTEMA");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLocaleProvider = new javax.swing.JLabel();
        txtCPF = new javax.swing.JLabel();
        inputCPFOrCNPJ = new javax.swing.JTextField();
        buttonLocale = new javax.swing.JButton();
        buttonAllProviders = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Localizar Fornecedor");
        setResizable(false);
        getContentPane().setLayout(null);

        txtLocaleProvider.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtLocaleProvider.setText("LOCALIZAR FORNECEDORES");
        getContentPane().add(txtLocaleProvider);
        txtLocaleProvider.setBounds(30, 10, 350, 32);

        txtCPF.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCPF.setText("CPF / CNPJ");
        getContentPane().add(txtCPF);
        txtCPF.setBounds(30, 60, 120, 20);

        inputCPFOrCNPJ.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputCPFOrCNPJ);
        inputCPFOrCNPJ.setBounds(30, 90, 220, 24);

        buttonLocale.setText("LOCALIZAR");
        buttonLocale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLocaleActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLocale);
        buttonLocale.setBounds(30, 130, 100, 25);

        buttonAllProviders.setText("TODOS OS FORNECEDORES");
        buttonAllProviders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllProvidersActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAllProviders);
        buttonAllProviders.setBounds(160, 130, 200, 25);

        setSize(new java.awt.Dimension(412, 216));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLocaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLocaleActionPerformed
        if(!inputCPFOrCNPJ.getText().equals("")){
            setProvider();
        }
        else{
            JOptionPane.showMessageDialog(null, "POR FAVOR, DIGITE UM CPF OU CNPJ!");
        }
    }//GEN-LAST:event_buttonLocaleActionPerformed

    private void buttonAllProvidersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllProvidersActionPerformed
        AllProviders allProviders = new AllProviders();
        this.dispose();
        allProviders.setVisible(true);
    }//GEN-LAST:event_buttonAllProvidersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocaleProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocaleProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocaleProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocaleProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocaleProvider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAllProviders;
    private javax.swing.JButton buttonLocale;
    private javax.swing.JTextField inputCPFOrCNPJ;
    private javax.swing.JLabel txtCPF;
    private javax.swing.JLabel txtLocaleProvider;
    // End of variables declaration//GEN-END:variables
}
