package screens;

import functioncontroller.ScreenUserSize;
import submenus.BillMenu;

public class MainMenu extends javax.swing.JFrame {
    public MainMenu() {
        initComponents();
        ScreenUserSize screenUserSize = new ScreenUserSize();
        this.setSize(screenUserSize.sizeOfScreen(), 197);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonFindOS = new javax.swing.JButton();
        buttonOrder = new javax.swing.JButton();
        buttonAddOS = new javax.swing.JButton();
        buttonEditOS = new javax.swing.JButton();
        buttonStock = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        txtAddOS = new javax.swing.JLabel();
        txtFindOS = new javax.swing.JLabel();
        txtEditOS = new javax.swing.JLabel();
        txtOrder = new javax.swing.JLabel();
        txtStock = new javax.swing.JLabel();
        txtLogout = new javax.swing.JLabel();
        buttonAddOS1 = new javax.swing.JButton();
        txtAddOS1 = new javax.swing.JLabel();
        buttonAddOS2 = new javax.swing.JButton();
        txtAddOS2 = new javax.swing.JLabel();
        txtStock1 = new javax.swing.JLabel();
        buttonStock1 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        separator8 = new javax.swing.JPopupMenu.Separator();
        opcBackup = new javax.swing.JMenuItem();
        optRestore = new javax.swing.JMenuItem();
        separator2 = new javax.swing.JPopupMenu.Separator();
        optUser = new javax.swing.JMenuItem();
        separator3 = new javax.swing.JPopupMenu.Separator();
        opcLogout = new javax.swing.JMenuItem();
        opcClose = new javax.swing.JMenuItem();
        menuFind = new javax.swing.JMenu();
        optLocalizeOS = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        menuOrder = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        menuManual = new javax.swing.JMenu();
        optAddManual = new javax.swing.JMenuItem();
        optFindManual = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        menuStock = new javax.swing.JMenu();
        optAddItemStock = new javax.swing.JMenuItem();
        optFindItemStock = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        optMoreRequestesItemsStock = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        menuBacklog = new javax.swing.JMenu();
        optAllPartsInTestRoom = new javax.swing.JMenuItem();
        optPartsOver7Days = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        optSuport = new javax.swing.JMenuItem();
        separator7 = new javax.swing.JPopupMenu.Separator();
        optAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MARKET SYSTEM");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        buttonFindOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product.png"))); // NOI18N
        buttonFindOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFindOSActionPerformed(evt);
            }
        });

        buttonOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stock.png"))); // NOI18N
        buttonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrderActionPerformed(evt);
            }
        });

        buttonAddOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cashier.png"))); // NOI18N
        buttonAddOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddOSActionPerformed(evt);
            }
        });

        buttonEditOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/orderClient.png"))); // NOI18N
        buttonEditOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditOSActionPerformed(evt);
            }
        });

        buttonStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill.png"))); // NOI18N
        buttonStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStockActionPerformed(evt);
            }
        });

        buttonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        txtAddOS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAddOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAddOS.setText("CAIXA");
        txtAddOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddOSMouseClicked(evt);
            }
        });

        txtFindOS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtFindOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFindOS.setText("PRODUTO");
        txtFindOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFindOSMouseClicked(evt);
            }
        });

        txtEditOS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtEditOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEditOS.setText("PEDIDOS");
        txtEditOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEditOSMouseClicked(evt);
            }
        });

        txtOrder.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtOrder.setText("ESTOQUE");
        txtOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOrderMouseClicked(evt);
            }
        });

        txtStock.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStock.setText("CONTAS");
        txtStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStockMouseClicked(evt);
            }
        });

        txtLogout.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogout.setText("LOGOUT");
        txtLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLogoutMouseClicked(evt);
            }
        });

        buttonAddOS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/client.png"))); // NOI18N
        buttonAddOS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddOS1ActionPerformed(evt);
            }
        });

        txtAddOS1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAddOS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAddOS1.setText("CLIENTE");
        txtAddOS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddOS1MouseClicked(evt);
            }
        });

        buttonAddOS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sale.png"))); // NOI18N
        buttonAddOS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddOS2ActionPerformed(evt);
            }
        });

        txtAddOS2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAddOS2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAddOS2.setText("VENDA");
        txtAddOS2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddOS2MouseClicked(evt);
            }
        });

        txtStock1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStock1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStock1.setText("AGENDA");
        txtStock1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStock1MouseClicked(evt);
            }
        });

        buttonStock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diary.png"))); // NOI18N
        buttonStock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStock1ActionPerformed(evt);
            }
        });

        menuFile.setText("Arquivo");
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });
        menuFile.add(separator8);

        opcBackup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        opcBackup.setText("Backup");
        menuFile.add(opcBackup);

        optRestore.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        optRestore.setText("Restaurar");
        menuFile.add(optRestore);
        menuFile.add(separator2);

        optUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        optUser.setText("Usuário");
        optUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optUserActionPerformed(evt);
            }
        });
        menuFile.add(optUser);
        menuFile.add(separator3);

        opcLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        opcLogout.setText("Logout");
        opcLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcLogoutActionPerformed(evt);
            }
        });
        menuFile.add(opcLogout);

        opcClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        opcClose.setText("Sair");
        opcClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcCloseActionPerformed(evt);
            }
        });
        menuFile.add(opcClose);

        menuBar.add(menuFile);

        menuFind.setText("Venda");

        optLocalizeOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        optLocalizeOS.setText("Nova Venda");
        optLocalizeOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optLocalizeOSActionPerformed(evt);
            }
        });
        menuFind.add(optLocalizeOS);

        jMenuItem3.setText("Localizar Venda");
        menuFind.add(jMenuItem3);

        jMenuItem4.setText("Editar Venda");
        menuFind.add(jMenuItem4);

        jMenuItem5.setText("Excluir Venda");
        menuFind.add(jMenuItem5);

        jMenuItem10.setText("Venda Pendente?");
        menuFind.add(jMenuItem10);

        menuBar.add(menuFind);

        menuOrder.setText("Pedidos");

        jMenuItem6.setText("Novo Pedido");
        menuOrder.add(jMenuItem6);

        jMenuItem7.setText("Localizar Pedido");
        menuOrder.add(jMenuItem7);

        jMenuItem8.setText("Editar Pedido");
        menuOrder.add(jMenuItem8);

        jMenuItem9.setText("Excluir Pedido");
        menuOrder.add(jMenuItem9);

        jMenuItem11.setText("Pedido Pendente");
        menuOrder.add(jMenuItem11);

        jMenuItem12.setText("Pedidos Cancelados");
        menuOrder.add(jMenuItem12);

        menuBar.add(menuOrder);

        menuManual.setText("Produtos");

        optAddManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        optAddManual.setText("Adicionar Produto");
        optAddManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAddManualActionPerformed(evt);
            }
        });
        menuManual.add(optAddManual);

        optFindManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK));
        optFindManual.setText("Localizar Produto");
        optFindManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optFindManualActionPerformed(evt);
            }
        });
        menuManual.add(optFindManual);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("Editar Produto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuManual.add(jMenuItem1);

        jMenuItem13.setText("Excluir Produto");
        menuManual.add(jMenuItem13);

        menuBar.add(menuManual);

        menuStock.setText("Estoque");

        optAddItemStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        optAddItemStock.setText("Adicionar itens ao estoque");
        optAddItemStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAddItemStockActionPerformed(evt);
            }
        });
        menuStock.add(optAddItemStock);

        optFindItemStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        optFindItemStock.setText("Localizar itens do estoque");
        optFindItemStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optFindItemStockActionPerformed(evt);
            }
        });
        menuStock.add(optFindItemStock);

        jMenuItem14.setText("Editar itens do estoque");
        menuStock.add(jMenuItem14);

        jMenuItem15.setText("Excluir itens do estoque");
        menuStock.add(jMenuItem15);

        optMoreRequestesItemsStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        optMoreRequestesItemsStock.setText("Itens mais requisitados no estoque");
        optMoreRequestesItemsStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optMoreRequestesItemsStockActionPerformed(evt);
            }
        });
        menuStock.add(optMoreRequestesItemsStock);

        jMenuItem22.setText("Inventário");
        menuStock.add(jMenuItem22);

        menuBar.add(menuStock);

        menuBacklog.setText("Clientes");

        optAllPartsInTestRoom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        optAllPartsInTestRoom.setText("Adicionar Cliente");
        optAllPartsInTestRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAllPartsInTestRoomActionPerformed(evt);
            }
        });
        menuBacklog.add(optAllPartsInTestRoom);

        optPartsOver7Days.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        optPartsOver7Days.setText("Localizar Cliente");
        optPartsOver7Days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optPartsOver7DaysActionPerformed(evt);
            }
        });
        menuBacklog.add(optPartsOver7Days);

        jMenuItem16.setText("Editar Cliente");
        menuBacklog.add(jMenuItem16);

        jMenuItem17.setText("excluir Cliente");
        menuBacklog.add(jMenuItem17);

        menuBar.add(menuBacklog);

        menuReport.setText("Relatórios");

        jMenuItem18.setText("Vendas do Mês");
        menuReport.add(jMenuItem18);

        jMenuItem19.setText("Movimentação no Caixa");
        menuReport.add(jMenuItem19);

        jMenuItem20.setText("Itens mais vendidos");
        menuReport.add(jMenuItem20);

        jMenuItem21.setText("Itens menos vendidos");
        menuReport.add(jMenuItem21);

        jMenuItem23.setText("Venda dos funcionários");
        menuReport.add(jMenuItem23);

        jMenuItem24.setText("Gastos do mês");
        menuReport.add(jMenuItem24);

        menuBar.add(menuReport);

        menuAbout.setText("Ajuda");

        optSuport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        optSuport.setText("Suporte");
        menuAbout.add(optSuport);
        menuAbout.add(separator7);

        optAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        optAbout.setText("Sobre");
        menuAbout.add(optAbout);

        menuBar.add(menuAbout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddOS, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddOS, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddOS2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddOS2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddOS1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddOS1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonFindOS, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFindOS, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEditOS, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditOS, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonStock, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStock1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonAddOS2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAddOS2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonAddOS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAddOS))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonAddOS1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAddOS1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(buttonFindOS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFindOS))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonEditOS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEditOS))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtOrder))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonStock, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStock)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtLogout))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1318, 197);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void optPartsOver7DaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optPartsOver7DaysActionPerformed
        
    }//GEN-LAST:event_optPartsOver7DaysActionPerformed

    private void optAllPartsInTestRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAllPartsInTestRoomActionPerformed
        
    }//GEN-LAST:event_optAllPartsInTestRoomActionPerformed

    private void optMoreRequestesItemsStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optMoreRequestesItemsStockActionPerformed
        
    }//GEN-LAST:event_optMoreRequestesItemsStockActionPerformed

    private void optFindItemStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optFindItemStockActionPerformed
        
    }//GEN-LAST:event_optFindItemStockActionPerformed

    private void optAddItemStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAddItemStockActionPerformed
        
    }//GEN-LAST:event_optAddItemStockActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void optFindManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optFindManualActionPerformed
        
    }//GEN-LAST:event_optFindManualActionPerformed

    private void optAddManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAddManualActionPerformed
        
    }//GEN-LAST:event_optAddManualActionPerformed

    private void optLocalizeOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optLocalizeOSActionPerformed
        
    }//GEN-LAST:event_optLocalizeOSActionPerformed

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed

    }//GEN-LAST:event_menuFileActionPerformed

    private void opcCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcCloseActionPerformed
        
    }//GEN-LAST:event_opcCloseActionPerformed

    private void opcLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcLogoutActionPerformed
        
    }//GEN-LAST:event_opcLogoutActionPerformed

    private void optUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optUserActionPerformed
        
    }//GEN-LAST:event_optUserActionPerformed

    private void txtAddOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddOSMouseClicked
        
    }//GEN-LAST:event_txtAddOSMouseClicked

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void txtLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogoutMouseClicked
        
    }//GEN-LAST:event_txtLogoutMouseClicked

    private void buttonStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStockActionPerformed
        
    }//GEN-LAST:event_buttonStockActionPerformed

    private void txtStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStockMouseClicked
        
    }//GEN-LAST:event_txtStockMouseClicked

    private void txtOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOrderMouseClicked
        
    }//GEN-LAST:event_txtOrderMouseClicked

    private void txtAddOS2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddOS2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddOS2MouseClicked

    private void buttonAddOS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddOS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddOS2ActionPerformed

    private void txtAddOS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddOS1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddOS1MouseClicked

    private void buttonAddOS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddOS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddOS1ActionPerformed

    private void buttonEditOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditOSActionPerformed
        
    }//GEN-LAST:event_buttonEditOSActionPerformed

    private void buttonAddOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddOSActionPerformed
        BillMenu billMenu = new BillMenu();
        billMenu.setVisible(true);
    }//GEN-LAST:event_buttonAddOSActionPerformed

    private void buttonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrderActionPerformed
        
    }//GEN-LAST:event_buttonOrderActionPerformed

    private void txtEditOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEditOSMouseClicked
        
    }//GEN-LAST:event_txtEditOSMouseClicked

    private void buttonFindOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFindOSActionPerformed
        
    }//GEN-LAST:event_buttonFindOSActionPerformed

    private void txtFindOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFindOSMouseClicked
        
    }//GEN-LAST:event_txtFindOSMouseClicked

    private void txtStock1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStock1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStock1MouseClicked

    private void buttonStock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStock1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonStock1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddOS;
    private javax.swing.JButton buttonAddOS1;
    private javax.swing.JButton buttonAddOS2;
    private javax.swing.JButton buttonEditOS;
    private javax.swing.JButton buttonFindOS;
    private javax.swing.JButton buttonLogout;
    public static javax.swing.JButton buttonOrder;
    private javax.swing.JButton buttonStock;
    private javax.swing.JButton buttonStock1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuBacklog;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuFind;
    private javax.swing.JMenu menuManual;
    private javax.swing.JMenu menuOrder;
    private javax.swing.JMenu menuReport;
    private javax.swing.JMenu menuStock;
    private javax.swing.JMenuItem opcBackup;
    private javax.swing.JMenuItem opcClose;
    private javax.swing.JMenuItem opcLogout;
    private javax.swing.JMenuItem optAbout;
    private javax.swing.JMenuItem optAddItemStock;
    private javax.swing.JMenuItem optAddManual;
    private javax.swing.JMenuItem optAllPartsInTestRoom;
    private javax.swing.JMenuItem optFindItemStock;
    private javax.swing.JMenuItem optFindManual;
    private javax.swing.JMenuItem optLocalizeOS;
    private javax.swing.JMenuItem optMoreRequestesItemsStock;
    private javax.swing.JMenuItem optPartsOver7Days;
    private javax.swing.JMenuItem optRestore;
    private javax.swing.JMenuItem optSuport;
    private javax.swing.JMenuItem optUser;
    private javax.swing.JPopupMenu.Separator separator2;
    private javax.swing.JPopupMenu.Separator separator3;
    private javax.swing.JPopupMenu.Separator separator7;
    private javax.swing.JPopupMenu.Separator separator8;
    private javax.swing.JLabel txtAddOS;
    private javax.swing.JLabel txtAddOS1;
    private javax.swing.JLabel txtAddOS2;
    private javax.swing.JLabel txtEditOS;
    private javax.swing.JLabel txtFindOS;
    private javax.swing.JLabel txtLogout;
    private javax.swing.JLabel txtOrder;
    private javax.swing.JLabel txtStock;
    private javax.swing.JLabel txtStock1;
    // End of variables declaration//GEN-END:variables
}
