/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author Alunos
 */
public class NewClient extends javax.swing.JFrame {

    /**
     * Creates new form NewClient
     */
    public NewClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Data de Nascimento");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(535, 95, 175, 24);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(45, 95, 52, 24);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("CPF");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 95, 36, 24);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Telefone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(45, 185, 77, 24);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("CEP");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(45, 265, 37, 24);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Rua");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 265, 34, 24);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Nº");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(535, 265, 20, 24);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Complemento");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(45, 350, 124, 24);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("E-mail");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(535, 185, 55, 24);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Celular");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(290, 185, 62, 24);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Cadastro de Cliente");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(268, 40, 225, 32);

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(45, 125, 219, 30);

        jFormattedTextField1.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(290, 125, 130, 30);

        jFormattedTextField2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(535, 125, 159, 30);

        jFormattedTextField3.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(jFormattedTextField3);
        jFormattedTextField3.setBounds(45, 215, 184, 30);

        jFormattedTextField4.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(jFormattedTextField4);
        jFormattedTextField4.setBounds(290, 215, 140, 30);

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(535, 215, 185, 30);

        jFormattedTextField5.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(jFormattedTextField5);
        jFormattedTextField5.setBounds(45, 295, 194, 30);

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(290, 295, 189, 30);

        jTextField4.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(535, 295, 98, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(43, 382, 553, 150);

        jButton1.setText("FOTO");
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 460, 61, 30);

        jButton2.setText("SALVAR");
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 500, 80, 30);

        setSize(new java.awt.Dimension(765, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
