/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class NewProvider extends javax.swing.JFrame {

    /**
     * Creates new form NewProvider
     */
    public NewProvider() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNewProvider = new javax.swing.JLabel();
        txtCPFAndCNPJ = new javax.swing.JLabel();
        inputCPFAndCNPJ = new javax.swing.JTextField();
        txtFantasyName = new javax.swing.JLabel();
        inputFantasyName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JLabel();
        inputPhone = new javax.swing.JTextField();
        txtCep = new javax.swing.JLabel();
        inputCep = new javax.swing.JTextField();
        txtAdress = new javax.swing.JLabel();
        inputAdress = new javax.swing.JTextField();
        txtCity = new javax.swing.JLabel();
        inputCity = new javax.swing.JTextField();
        txtState = new javax.swing.JLabel();
        inputState = new javax.swing.JComboBox<>();
        txtNeighBorhood = new javax.swing.JLabel();
        inputNeighborhood = new javax.swing.JTextField();
        txtEmail = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        txtCompanyName = new javax.swing.JLabel();
        inputCompanyName = new javax.swing.JTextField();
        txtFax = new javax.swing.JLabel();
        inputFax = new javax.swing.JTextField();
        txtNumber = new javax.swing.JLabel();
        inputNumber = new javax.swing.JTextField();
        txtCellPhone = new javax.swing.JLabel();
        inputCellPhone = new javax.swing.JTextField();
        txtObservation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputObservation = new javax.swing.JTextArea();
        buttonSave = new javax.swing.JButton();
        txtComplement = new javax.swing.JLabel();
        inputComplement = new javax.swing.JTextField();
        txtCode = new javax.swing.JLabel();
        inputCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Fornecedor");
        setResizable(false);
        getContentPane().setLayout(null);

        txtNewProvider.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtNewProvider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNewProvider.setText("NOVO FORNECEDOR");
        getContentPane().add(txtNewProvider);
        txtNewProvider.setBounds(260, 20, 320, 32);

        txtCPFAndCNPJ.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCPFAndCNPJ.setText("CPF / CNPJ");
        getContentPane().add(txtCPFAndCNPJ);
        txtCPFAndCNPJ.setBounds(180, 70, 100, 20);

        inputCPFAndCNPJ.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputCPFAndCNPJ);
        inputCPFAndCNPJ.setBounds(180, 100, 160, 30);

        txtFantasyName.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtFantasyName.setText("Nome Fantasia");
        getContentPane().add(txtFantasyName);
        txtFantasyName.setBounds(370, 70, 120, 20);

        inputFantasyName.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputFantasyName);
        inputFantasyName.setBounds(370, 100, 200, 30);

        txtPhone.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtPhone.setText("Telefone");
        getContentPane().add(txtPhone);
        txtPhone.setBounds(20, 150, 64, 20);

        inputPhone.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputPhone);
        inputPhone.setBounds(20, 180, 140, 30);

        txtCep.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCep.setText("CEP");
        getContentPane().add(txtCep);
        txtCep.setBounds(20, 240, 31, 20);

        inputCep.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputCep);
        inputCep.setBounds(20, 270, 130, 30);

        txtAdress.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtAdress.setText("Endereço");
        getContentPane().add(txtAdress);
        txtAdress.setBounds(240, 240, 69, 20);

        inputAdress.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputAdress);
        inputAdress.setBounds(240, 270, 280, 30);

        txtCity.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCity.setText("Cidade");
        getContentPane().add(txtCity);
        txtCity.setBounds(310, 320, 50, 20);

        inputCity.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputCity);
        inputCity.setBounds(310, 350, 180, 30);

        txtState.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtState.setText("Estado");
        getContentPane().add(txtState);
        txtState.setBounds(560, 320, 49, 20);

        inputState.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        inputState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONAR", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        getContentPane().add(inputState);
        inputState.setBounds(560, 350, 140, 30);

        txtNeighBorhood.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtNeighBorhood.setText("Bairro");
        getContentPane().add(txtNeighBorhood);
        txtNeighBorhood.setBounds(20, 320, 44, 20);

        inputNeighborhood.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputNeighborhood);
        inputNeighborhood.setBounds(20, 350, 220, 30);

        txtEmail.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtEmail.setText("Email");
        getContentPane().add(txtEmail);
        txtEmail.setBounds(590, 150, 38, 20);

        inputEmail.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputEmail);
        inputEmail.setBounds(590, 180, 210, 30);

        txtCompanyName.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCompanyName.setText("Razão Social");
        getContentPane().add(txtCompanyName);
        txtCompanyName.setBounds(590, 70, 120, 20);

        inputCompanyName.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputCompanyName);
        inputCompanyName.setBounds(590, 100, 210, 30);

        txtFax.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtFax.setText("Fax");
        getContentPane().add(txtFax);
        txtFax.setBounds(180, 150, 25, 20);

        inputFax.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputFax);
        inputFax.setBounds(180, 180, 170, 30);

        txtNumber.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtNumber.setText("Número");
        getContentPane().add(txtNumber);
        txtNumber.setBounds(590, 240, 60, 20);

        inputNumber.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputNumber);
        inputNumber.setBounds(590, 270, 130, 30);

        txtCellPhone.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCellPhone.setText("Celular");
        getContentPane().add(txtCellPhone);
        txtCellPhone.setBounds(370, 150, 80, 20);

        inputCellPhone.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputCellPhone);
        inputCellPhone.setBounds(370, 180, 170, 30);

        txtObservation.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtObservation.setText("Observação");
        getContentPane().add(txtObservation);
        txtObservation.setBounds(20, 480, 110, 20);

        inputObservation.setColumns(20);
        inputObservation.setRows(5);
        jScrollPane1.setViewportView(inputObservation);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 510, 600, 140);

        buttonSave.setText("SALVAR");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSave);
        buttonSave.setBounds(720, 620, 77, 32);

        txtComplement.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtComplement.setText("Complemento");
        getContentPane().add(txtComplement);
        txtComplement.setBounds(20, 400, 110, 20);

        inputComplement.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputComplement);
        inputComplement.setBounds(20, 430, 270, 30);

        txtCode.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCode.setText("Código");
        getContentPane().add(txtCode);
        txtCode.setBounds(20, 70, 100, 20);

        inputCode.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(inputCode);
        inputCode.setBounds(20, 100, 130, 30);

        setSize(new java.awt.Dimension(827, 696));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        if(txtNewProvider.getText().equals("NOVO FORNECEDOR")){
            JOptionPane.showMessageDialog(null, "FORNECEDOR CADASTRADO COM SUCESSO");
        }
        else if(txtNewProvider.getText().equals("EDITAR FORNECEDOR")){
            JOptionPane.showMessageDialog(null, "FORNECEDOR ATUALIZADO COM SUCESSO");
        }
        ProviderScreen providerScreen = new ProviderScreen();
        this.dispose();
        providerScreen.setVisible(true);
    }//GEN-LAST:event_buttonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProvider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSave;
    private javax.swing.JTextField inputAdress;
    private javax.swing.JTextField inputCPFAndCNPJ;
    private javax.swing.JTextField inputCellPhone;
    private javax.swing.JTextField inputCep;
    private javax.swing.JTextField inputCity;
    private javax.swing.JTextField inputCode;
    private javax.swing.JTextField inputCompanyName;
    private javax.swing.JTextField inputComplement;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputFantasyName;
    private javax.swing.JTextField inputFax;
    private javax.swing.JTextField inputNeighborhood;
    private javax.swing.JTextField inputNumber;
    private javax.swing.JTextArea inputObservation;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JComboBox<String> inputState;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtAdress;
    private javax.swing.JLabel txtCPFAndCNPJ;
    private javax.swing.JLabel txtCellPhone;
    private javax.swing.JLabel txtCep;
    private javax.swing.JLabel txtCity;
    private javax.swing.JLabel txtCode;
    private javax.swing.JLabel txtCompanyName;
    private javax.swing.JLabel txtComplement;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFantasyName;
    private javax.swing.JLabel txtFax;
    private javax.swing.JLabel txtNeighBorhood;
    public static javax.swing.JLabel txtNewProvider;
    private javax.swing.JLabel txtNumber;
    private javax.swing.JLabel txtObservation;
    private javax.swing.JLabel txtPhone;
    private javax.swing.JLabel txtState;
    // End of variables declaration//GEN-END:variables
}
