/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package screens;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class NewSchedule extends javax.swing.JFrame {

    /** Creates new form NewSchedule */
    public NewSchedule() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNewAppointment = new javax.swing.JLabel();
        txtNameAppointment = new javax.swing.JLabel();
        inputNameAppointment = new javax.swing.JTextField();
        txtAppointmentDate = new javax.swing.JLabel();
        inputAppointmentDate = new javax.swing.JTextField();
        txtAppointmentHour = new javax.swing.JLabel();
        inputAppointmentHour = new javax.swing.JTextField();
        txtAppointmentDescription = new javax.swing.JLabel();
        tableNewSchedule = new javax.swing.JScrollPane();
        inputAppointmentDescription = new javax.swing.JTextArea();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Compromisso");
        setResizable(false);
        getContentPane().setLayout(null);

        txtNewAppointment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtNewAppointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNewAppointment.setText("NOVO COMPROMISSO");
        getContentPane().add(txtNewAppointment);
        txtNewAppointment.setBounds(60, 10, 390, 29);

        txtNameAppointment.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtNameAppointment.setText("Nome do Compromisso");
        getContentPane().add(txtNameAppointment);
        txtNameAppointment.setBounds(30, 70, 170, 19);

        inputNameAppointment.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(inputNameAppointment);
        inputNameAppointment.setBounds(30, 100, 220, 25);

        txtAppointmentDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtAppointmentDate.setText("Data do Compromisso");
        getContentPane().add(txtAppointmentDate);
        txtAppointmentDate.setBounds(310, 70, 150, 19);

        inputAppointmentDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(inputAppointmentDate);
        inputAppointmentDate.setBounds(310, 100, 100, 25);

        txtAppointmentHour.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtAppointmentHour.setText("Horário do Compromisso");
        getContentPane().add(txtAppointmentHour);
        txtAppointmentHour.setBounds(30, 140, 180, 19);

        inputAppointmentHour.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(inputAppointmentHour);
        inputAppointmentHour.setBounds(30, 170, 60, 25);

        txtAppointmentDescription.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtAppointmentDescription.setText("Descrição do Compromisso");
        getContentPane().add(txtAppointmentDescription);
        txtAppointmentDescription.setBounds(30, 220, 180, 19);

        inputAppointmentDescription.setColumns(20);
        inputAppointmentDescription.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        inputAppointmentDescription.setRows(5);
        tableNewSchedule.setViewportView(inputAppointmentDescription);

        getContentPane().add(tableNewSchedule);
        tableNewSchedule.setBounds(30, 250, 420, 160);

        buttonSave.setText("SALVAR");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSave);
        buttonSave.setBounds(30, 440, 80, 23);

        buttonCancel.setText("CANCELAR");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCancel);
        buttonCancel.setBounds(150, 440, 100, 23);

        setSize(new java.awt.Dimension(495, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        if(txtNewAppointment.getText().equals("NOVO COMPROMISSO")){
            JOptionPane.showMessageDialog(null, "COMPROMISSO CADASTRADO COM SUCESSO");
        }
        else if(txtNewAppointment.getText().equals("EDITAR COMPROMISSO")){
            JOptionPane.showMessageDialog(null, "COMPROMISSO ATUALIZADO COM SUCESSO");
        }
        ScheduleScreen scheduleScreen = new ScheduleScreen();
        this.dispose();
        scheduleScreen.setVisible(true);
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        if(buttonCancel.getText().equals("CANCELAR")){
            this.dispose();
        }
        else if(buttonCancel.getText().equals("APAGAR")){
            JOptionPane.showMessageDialog(null, "COMPROMISSO APAGADO COM SUCESSO");
            this.dispose();
        }
    }//GEN-LAST:event_buttonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JTextField inputAppointmentDate;
    private javax.swing.JTextArea inputAppointmentDescription;
    private javax.swing.JTextField inputAppointmentHour;
    private javax.swing.JTextField inputNameAppointment;
    private javax.swing.JScrollPane tableNewSchedule;
    private javax.swing.JLabel txtAppointmentDate;
    private javax.swing.JLabel txtAppointmentDescription;
    private javax.swing.JLabel txtAppointmentHour;
    private javax.swing.JLabel txtNameAppointment;
    public static javax.swing.JLabel txtNewAppointment;
    // End of variables declaration//GEN-END:variables

}
