package screens;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import connectionbd.ConnectionModule;
import formattingmask.MaskCPFAndCNPJ;
import formattingmask.MaskCepAndHouseNumber;
import formattingmask.MaskJustNumbers;
import formattingmask.MaskPhone;
import functioncontroller.UpperLetter;
public class ProviderScreen extends javax.swing.JFrame {
    int x = 0;
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    PreparedStatement pst2 = null;
    ResultSet rs2 = null;
    public ProviderScreen() {
        initComponents();
        ConnectionModule connect = new ConnectionModule();
        connection = connect.getConnectionMySQL();
        outputFantasyName.setDocument(new UpperLetter());
        outputCompanyName.setDocument(new UpperLetter());
        outputEmail.setDocument(new UpperLetter());
        outputAdress.setDocument(new UpperLetter());
        outputNeighborhood.setDocument(new UpperLetter());
        outputCity.setDocument(new UpperLetter());
        outputComplement.setDocument(new UpperLetter());
        outputObservation.setDocument(new UpperLetter());
        outputCPFAndCNPJ.setDocument(new MaskCPFAndCNPJ());
        outputPhone.setDocument(new MaskPhone());
        outputCellPhone.setDocument(new MaskPhone());
        outputCep.setDocument(new MaskCepAndHouseNumber());
        outputNumber.setDocument(new MaskCepAndHouseNumber());
        outputCode.setDocument(new MaskJustNumbers());
    }
    private void setProvider(){
        String[] vect = this.getTitle().split(" ");
        int codeProvider = Integer.parseInt( vect[1] );
        String sql ="select cpf, fantasyName, companyName, phone, cellPhone, email, cep, street, houseNumber, neighborhood, city, state, complement, observation from provider where codeProvider=?";
        try {
            pst2=connection.prepareStatement(sql);
            pst2.setInt(1, codeProvider);
            rs2= pst2.executeQuery();
            if(rs2.next()){
                outputCPFAndCNPJ.setText(rs2.getString(1));
                outputFantasyName.setText(rs2.getString(2));
                outputCompanyName.setText(rs2.getString(3));
                outputPhone.setText(rs2.getString(4));
                outputCellPhone.setText(rs2.getString(5));
                outputEmail.setText(rs2.getString(6));
                outputCep.setText(rs2.getString(7));
                outputAdress.setText(rs2.getString(8));
                outputNumber.setText(rs2.getString(9));
                outputNeighborhood.setText(rs2.getString(10));
                outputCity.setText(rs2.getString(11));
                outputState.setSelectedItem(rs2.getString(12));
                outputComplement.setText(rs2.getString(13));
                outputObservation.setText(rs2.getString(14));
                outputCode.setText( Integer.toString( codeProvider) );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProvider = new javax.swing.JLabel();
        txtCPFAndCNPJ = new javax.swing.JLabel();
        outputCPFAndCNPJ = new javax.swing.JTextField();
        txtFantasyName = new javax.swing.JLabel();
        outputFantasyName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JLabel();
        outputPhone = new javax.swing.JTextField();
        txtCep = new javax.swing.JLabel();
        outputCep = new javax.swing.JTextField();
        txtAdress = new javax.swing.JLabel();
        outputAdress = new javax.swing.JTextField();
        txtCity = new javax.swing.JLabel();
        outputCity = new javax.swing.JTextField();
        txtState = new javax.swing.JLabel();
        outputState = new javax.swing.JComboBox<>();
        txtNeighBorhood = new javax.swing.JLabel();
        outputNeighborhood = new javax.swing.JTextField();
        txtEmail = new javax.swing.JLabel();
        outputEmail = new javax.swing.JTextField();
        txtCompanyName = new javax.swing.JLabel();
        outputCompanyName = new javax.swing.JTextField();
        txtNumber = new javax.swing.JLabel();
        outputNumber = new javax.swing.JTextField();
        txtCellPhone = new javax.swing.JLabel();
        outputCellPhone = new javax.swing.JTextField();
        txtObservation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputObservation = new javax.swing.JTextArea();
        buttonEdit = new javax.swing.JButton();
        txtComplement = new javax.swing.JLabel();
        outputComplement = new javax.swing.JTextField();
        txtCode = new javax.swing.JLabel();
        outputCode = new javax.swing.JTextField();
        buttonPrinter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fornecedor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        txtProvider.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtProvider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProvider.setText("FORNECEDOR");
        getContentPane().add(txtProvider);
        txtProvider.setBounds(290, 20, 260, 32);

        txtCPFAndCNPJ.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCPFAndCNPJ.setText("CPF / CNPJ");
        getContentPane().add(txtCPFAndCNPJ);
        txtCPFAndCNPJ.setBounds(20, 150, 100, 20);

        outputCPFAndCNPJ.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(outputCPFAndCNPJ);
        outputCPFAndCNPJ.setBounds(20, 180, 160, 30);

        txtFantasyName.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtFantasyName.setText("Nome Fantasia");
        getContentPane().add(txtFantasyName);
        txtFantasyName.setBounds(170, 70, 120, 20);

        outputFantasyName.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(outputFantasyName);
        outputFantasyName.setBounds(170, 100, 340, 30);

        txtPhone.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtPhone.setText("Telefone");
        getContentPane().add(txtPhone);
        txtPhone.setBounds(200, 150, 64, 20);

        outputPhone.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(outputPhone);
        outputPhone.setBounds(200, 180, 140, 30);

        txtCep.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCep.setText("CEP");
        getContentPane().add(txtCep);
        txtCep.setBounds(20, 230, 31, 20);

        outputCep.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(outputCep);
        outputCep.setBounds(20, 260, 130, 30);

        txtAdress.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtAdress.setText("Endereço");
        getContentPane().add(txtAdress);
        txtAdress.setBounds(190, 230, 69, 20);

        outputAdress.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(outputAdress);
        outputAdress.setBounds(190, 260, 460, 30);

        txtCity.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCity.setText("Cidade");
        getContentPane().add(txtCity);
        txtCity.setBounds(430, 320, 50, 20);

        outputCity.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(outputCity);
        outputCity.setBounds(430, 350, 250, 30);

        txtState.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtState.setText("Estado");
        getContentPane().add(txtState);
        txtState.setBounds(720, 320, 49, 20);

        outputState.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        outputState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONAR", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        outputState.setEnabled(false);
        getContentPane().add(outputState);
        outputState.setBounds(720, 350, 140, 30);

        txtNeighBorhood.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtNeighBorhood.setText("Bairro");
        getContentPane().add(txtNeighBorhood);
        txtNeighBorhood.setBounds(20, 320, 44, 20);

        outputNeighborhood.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(outputNeighborhood);
        outputNeighborhood.setBounds(20, 350, 380, 30);

        txtEmail.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtEmail.setText("Email");
        getContentPane().add(txtEmail);
        txtEmail.setBounds(550, 150, 38, 20);

        outputEmail.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(outputEmail);
        outputEmail.setBounds(550, 180, 310, 30);

        txtCompanyName.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCompanyName.setText("Razão Social");
        getContentPane().add(txtCompanyName);
        txtCompanyName.setBounds(530, 70, 120, 20);

        outputCompanyName.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(outputCompanyName);
        outputCompanyName.setBounds(530, 100, 330, 30);

        txtNumber.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtNumber.setText("Número");
        getContentPane().add(txtNumber);
        txtNumber.setBounds(690, 230, 60, 20);

        outputNumber.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(outputNumber);
        outputNumber.setBounds(690, 260, 90, 30);

        txtCellPhone.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCellPhone.setText("Celular");
        getContentPane().add(txtCellPhone);
        txtCellPhone.setBounds(360, 150, 80, 20);

        outputCellPhone.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(outputCellPhone);
        outputCellPhone.setBounds(360, 180, 170, 30);

        txtObservation.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtObservation.setText("Observação");
        getContentPane().add(txtObservation);
        txtObservation.setBounds(20, 480, 110, 20);

        outputObservation.setColumns(20);
        outputObservation.setRows(5);
        jScrollPane1.setViewportView(outputObservation);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 510, 710, 140);

        buttonEdit.setText("EDITAR");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEdit);
        buttonEdit.setBounds(780, 580, 80, 25);

        txtComplement.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtComplement.setText("Complemento");
        getContentPane().add(txtComplement);
        txtComplement.setBounds(20, 400, 110, 20);

        outputComplement.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        getContentPane().add(outputComplement);
        outputComplement.setBounds(20, 430, 270, 30);

        txtCode.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtCode.setText("Código");
        getContentPane().add(txtCode);
        txtCode.setBounds(20, 70, 100, 20);

        outputCode.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        outputCode.setEnabled(false);
        getContentPane().add(outputCode);
        outputCode.setBounds(20, 100, 130, 30);

        buttonPrinter.setText("IMPRIMIR");
        getContentPane().add(buttonPrinter);
        buttonPrinter.setBounds(770, 620, 90, 25);

        setSize(new java.awt.Dimension(897, 699));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        NewProvider newProvider = new NewProvider();
        newProvider.txtNewProvider.setText("EDITAR FORNECEDOR");
        newProvider.setTitle("Editar Fornecedor: " + outputCode.getText());
        this.dispose();
        newProvider.setVisible(true);
    }//GEN-LAST:event_buttonEditActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(x==0){
            x++;
            setProvider();
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProviderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProviderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProviderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProviderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProviderScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonPrinter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField outputAdress;
    private javax.swing.JTextField outputCPFAndCNPJ;
    private javax.swing.JTextField outputCellPhone;
    private javax.swing.JTextField outputCep;
    private javax.swing.JTextField outputCity;
    private javax.swing.JTextField outputCode;
    private javax.swing.JTextField outputCompanyName;
    private javax.swing.JTextField outputComplement;
    private javax.swing.JTextField outputEmail;
    private javax.swing.JTextField outputFantasyName;
    private javax.swing.JTextField outputNeighborhood;
    private javax.swing.JTextField outputNumber;
    private javax.swing.JTextArea outputObservation;
    private javax.swing.JTextField outputPhone;
    private javax.swing.JComboBox<String> outputState;
    private javax.swing.JLabel txtAdress;
    private javax.swing.JLabel txtCPFAndCNPJ;
    private javax.swing.JLabel txtCellPhone;
    private javax.swing.JLabel txtCep;
    private javax.swing.JLabel txtCity;
    private javax.swing.JLabel txtCode;
    private javax.swing.JLabel txtCompanyName;
    private javax.swing.JLabel txtComplement;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFantasyName;
    private javax.swing.JLabel txtNeighBorhood;
    private javax.swing.JLabel txtNumber;
    private javax.swing.JLabel txtObservation;
    private javax.swing.JLabel txtPhone;
    private javax.swing.JLabel txtProvider;
    private javax.swing.JLabel txtState;
    // End of variables declaration//GEN-END:variables
}
