/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author willi_bg
 */
public class TakePictureOrChoose extends javax.swing.JFrame {
    public NewClient newClient;
    /**
     * Creates new form TakePictureOrChoose
     */
    public TakePictureOrChoose() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTakePicture = new javax.swing.JButton();
        buttonChoosePicture = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Upload de Imagem");
        getContentPane().setLayout(null);

        buttonTakePicture.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        buttonTakePicture.setText("TIRAR FOTO");
        buttonTakePicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTakePictureActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTakePicture);
        buttonTakePicture.setBounds(50, 40, 160, 27);

        buttonChoosePicture.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        buttonChoosePicture.setText("ESCOLHER FOTO");
        buttonChoosePicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChoosePictureActionPerformed(evt);
            }
        });
        getContentPane().add(buttonChoosePicture);
        buttonChoosePicture.setBounds(50, 80, 160, 27);

        setSize(new java.awt.Dimension(285, 193));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChoosePictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChoosePictureActionPerformed
        this.dispose();
        newClient.imageAdress = newClient.getImageAdress.getAdress();
        if(!newClient.imageAdress.equals(null)){
            newClient.buttonPhoto.setText("");
        }
        ImageIcon imagen = new ImageIcon(newClient.imageAdress);
        newClient.buttonPhoto.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(newClient.buttonPhoto.getWidth(), newClient.buttonPhoto.getHeight(), Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_buttonChoosePictureActionPerformed

    private void buttonTakePictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTakePictureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTakePictureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakePictureOrChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakePictureOrChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakePictureOrChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakePictureOrChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakePictureOrChoose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChoosePicture;
    private javax.swing.JButton buttonTakePicture;
    // End of variables declaration//GEN-END:variables
}
