/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.downloadscreen;
import functioncontroller.LimitNumberCharacters;
import javax.swing.JOptionPane;
import setsoons.SetAndOrganizeSoons;

/**
 *
 * @author willi
 */
public class DownloadOS extends setsoons.AuxiliaryJFrame {

    /**
     * Creates new form DownloadOS
     */
    public DownloadOS() {
        initComponents();
        showSerial.setDocument(new LimitNumberCharacters());
    }
    SetAndOrganizeSoons setAndOrganizeSoons = new SetAndOrganizeSoons();
    boolean inicializedWindow = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soonTavile = new javax.swing.JLabel();
        soonProxxi = new javax.swing.JLabel();
        txtDownloadOS = new javax.swing.JLabel();
        txtTimeSpent = new javax.swing.JLabel();
        inputTimeSpent = new javax.swing.JFormattedTextField();
        txtRepairedModule = new javax.swing.JLabel();
        inputRepairedModule = new javax.swing.JComboBox<>();
        txtStatus = new javax.swing.JLabel();
        inputStatus = new javax.swing.JComboBox<>();
        txtModuleSituation = new javax.swing.JLabel();
        inputModuleSituation = new javax.swing.JComboBox<>();
        inputLowConsumables = new javax.swing.JCheckBox();
        txtTechnicianRepaired = new javax.swing.JLabel();
        inputTechnicianRepaired = new javax.swing.JComboBox<>();
        txtSerial = new javax.swing.JLabel();
        txtCode = new javax.swing.JLabel();
        showCode = new javax.swing.JTextField();
        txtName = new javax.swing.JLabel();
        showName = new javax.swing.JTextField();
        txtSolution = new javax.swing.JLabel();
        solutionBox = new javax.swing.JScrollPane();
        inputSolution = new javax.swing.JTextArea();
        buttonSaveAttendance = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        showSerial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baixar OS");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtDownloadOS.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtDownloadOS.setText("Baixar OS");

        txtTimeSpent.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTimeSpent.setText("Tempo gasto (HH:MM)");

        try {
            inputTimeSpent.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputTimeSpent.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtRepairedModule.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRepairedModule.setText("Módulo reparado");

        inputRepairedModule.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputRepairedModule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        txtStatus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStatus.setText("Status");

        inputStatus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtModuleSituation.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtModuleSituation.setText("Situação do módulo");

        inputModuleSituation.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputModuleSituation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        inputLowConsumables.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputLowConsumables.setText("Baixar consumíveis");

        txtTechnicianRepaired.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTechnicianRepaired.setText("Técnico que reparou");

        inputTechnicianRepaired.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputTechnicianRepaired.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtSerial.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSerial.setText("Serial");

        txtCode.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCode.setText("Código");

        showCode.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        showCode.setText("372250034000R");
        showCode.setEnabled(false);

        txtName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtName.setText("Nome");

        showName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        showName.setText("ASSY PRESENTER R/A SHORT");
        showName.setEnabled(false);

        txtSolution.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSolution.setText("Solução");

        inputSolution.setColumns(20);
        inputSolution.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputSolution.setRows(5);
        solutionBox.setViewportView(inputSolution);

        buttonSaveAttendance.setText("Gravar Atendimento");
        buttonSaveAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveAttendanceActionPerformed(evt);
            }
        });

        jButton1.setText("LOCALIZAR");

        showSerial.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(soonTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(soonProxxi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(buttonSaveAttendance)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTimeSpent)
                        .addGap(36, 36, 36)
                        .addComponent(inputTimeSpent, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txtRepairedModule))
                    .addComponent(txtSolution)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(solutionBox, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputLowConsumables)
                                .addComponent(txtModuleSituation))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(338, 338, 338)
                                    .addComponent(inputRepairedModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(txtStatus)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inputStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(inputModuleSituation, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)
                                    .addComponent(txtTechnicianRepaired)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputTechnicianRepaired, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSerial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCode)
                        .addGap(18, 18, 18)
                        .addComponent(showCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(txtName)
                        .addGap(14, 14, 14)
                        .addComponent(showName, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDownloadOS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soonTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soonProxxi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDownloadOS)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerial)
                    .addComponent(txtCode)
                    .addComponent(showCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName)
                    .addComponent(showName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimeSpent)
                    .addComponent(inputTimeSpent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRepairedModule)
                    .addComponent(inputRepairedModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus)
                    .addComponent(inputStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModuleSituation)
                    .addComponent(inputModuleSituation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTechnicianRepaired)
                    .addComponent(inputTechnicianRepaired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(inputLowConsumables)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(txtSolution)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(solutionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSaveAttendance)
                .addGap(26, 26, 26))
        );

        setSize(new java.awt.Dimension(877, 622));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(inicializedWindow==false){
            inicializedWindow = true;
            setAndOrganizeSoons.SetSoons(this);
            setAndOrganizeSoons.SetLocationSoons(this, soonTavile.getX(), soonTavile.getY(), soonProxxi.getX(), soonProxxi.getY());
        }
    }//GEN-LAST:event_formWindowActivated

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        setAndOrganizeSoons.SetLocationSoons(this, soonTavile.getX(), soonTavile.getY(), soonProxxi.getX(), soonProxxi.getY());
    }//GEN-LAST:event_formComponentResized

    private void buttonSaveAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveAttendanceActionPerformed
        JOptionPane.showMessageDialog(null, "BAIXA DA OS CADASTRADA COM SUCESSO");
    }//GEN-LAST:event_buttonSaveAttendanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DownloadOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DownloadOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DownloadOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DownloadOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DownloadOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSaveAttendance;
    private javax.swing.JCheckBox inputLowConsumables;
    private javax.swing.JComboBox<String> inputModuleSituation;
    private javax.swing.JComboBox<String> inputRepairedModule;
    private javax.swing.JTextArea inputSolution;
    private javax.swing.JComboBox<String> inputStatus;
    private javax.swing.JComboBox<String> inputTechnicianRepaired;
    private javax.swing.JFormattedTextField inputTimeSpent;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField showCode;
    private javax.swing.JTextField showName;
    private javax.swing.JTextField showSerial;
    private javax.swing.JScrollPane solutionBox;
    public static javax.swing.JLabel soonProxxi;
    public static javax.swing.JLabel soonTavile;
    private javax.swing.JLabel txtCode;
    private javax.swing.JLabel txtDownloadOS;
    private javax.swing.JLabel txtModuleSituation;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtRepairedModule;
    private javax.swing.JLabel txtSerial;
    private javax.swing.JLabel txtSolution;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtTechnicianRepaired;
    private javax.swing.JLabel txtTimeSpent;
    // End of variables declaration//GEN-END:variables
}
