/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.files.editfiles;
import functionsuport.CallOrderEdit;
import functionsuport.CallOrderScreen;
import javax.swing.JOptionPane;
import setsoons.SetAndOrganizeSoons;

/**
 *
 * @author willi
 */
public class OrderEditOrder extends setsoons.AuxiliaryJFrame {

    /**
     * Creates new form EditOrder
     */
    public OrderEditOrder() {
        initComponents();
    }
    SetAndOrganizeSoons setAndOrganizeSoons = new SetAndOrganizeSoons();
    boolean inicializedWindow = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soonTavile = new javax.swing.JLabel();
        soonProxxi = new javax.swing.JLabel();
        txtCodePart = new javax.swing.JLabel();
        inputSupplierBranch = new javax.swing.JComboBox<>();
        inputRequestingBranch = new javax.swing.JComboBox<>();
        buttonRemoverOrder = new javax.swing.JButton();
        txtSupplierBranch = new javax.swing.JLabel();
        inputQuantityRequested = new javax.swing.JSpinner();
        txtRequestingBranch = new javax.swing.JLabel();
        buttonOrderEditOrder = new javax.swing.JButton();
        buttonAddNewOrder = new javax.swing.JButton();
        tableOfOrders = new javax.swing.JScrollPane();
        tablePartsOfOrder = new javax.swing.JTable();
        txtQuantityRequested = new javax.swing.JLabel();
        txtCodeOrder = new javax.swing.JLabel();
        inputCodePart = new javax.swing.JTextField();
        txtOrderEditOrder = new javax.swing.JLabel();
        buttonLocaleOrder = new javax.swing.JButton();
        inputCodeOrder = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Pedido");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtCodePart.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCodePart.setText("Código da peça");

        inputSupplierBranch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputSupplierBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        inputRequestingBranch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputRequestingBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonRemoverOrder.setText("REMOVER");

        txtSupplierBranch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSupplierBranch.setText("Filial Fornecedora");

        inputQuantityRequested.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputQuantityRequested.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        txtRequestingBranch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRequestingBranch.setText("Filial Solicitante");

        buttonOrderEditOrder.setText("SALVAR");
        buttonOrderEditOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrderEditOrderActionPerformed(evt);
            }
        });

        buttonAddNewOrder.setText("ADICIONAR");

        tablePartsOfOrder.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tablePartsOfOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código do Produto", "Descrição", "Quantidade"
            }
        ));
        tableOfOrders.setViewportView(tablePartsOfOrder);

        txtQuantityRequested.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtQuantityRequested.setText("Quantidade solicitada");

        txtCodeOrder.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCodeOrder.setText("Pedido");

        inputCodePart.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputCodePart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputCodePartKeyPressed(evt);
            }
        });

        txtOrderEditOrder.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtOrderEditOrder.setText("Editar Pedido");

        buttonLocaleOrder.setText("LOCALIZAR");

        inputCodeOrder.setForeground(new java.awt.Color(51, 51, 51));
        try {
            inputCodeOrder.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputCodeOrder.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(soonTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(soonProxxi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tableOfOrders)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRequestingBranch)
                            .addComponent(txtCodePart))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonLocaleOrder)
                                    .addComponent(inputCodePart, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addComponent(txtQuantityRequested, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(inputQuantityRequested, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(inputRequestingBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addComponent(txtSupplierBranch)
                                .addGap(26, 26, 26)
                                .addComponent(inputSupplierBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodeOrder)
                        .addGap(38, 38, 38)
                        .addComponent(inputCodeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonOrderEditOrder)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAddNewOrder)
                        .addGap(36, 36, 36)
                        .addComponent(buttonRemoverOrder)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtOrderEditOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soonTavile, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soonProxxi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(txtOrderEditOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodeOrder)
                    .addComponent(buttonLocaleOrder)
                    .addComponent(inputCodeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRequestingBranch)
                    .addComponent(inputRequestingBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSupplierBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupplierBranch))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodePart)
                    .addComponent(txtQuantityRequested)
                    .addComponent(inputQuantityRequested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCodePart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddNewOrder)
                    .addComponent(buttonRemoverOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(tableOfOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonOrderEditOrder)
                .addGap(15, 15, 15))
        );

        setSize(new java.awt.Dimension(1012, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputCodePartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCodePartKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodePartKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(inicializedWindow==false){
            inicializedWindow = true;
            setAndOrganizeSoons.SetSoons(this);
            setAndOrganizeSoons.SetLocationSoons(this, soonTavile.getX(), soonTavile.getY(), soonProxxi.getX(), soonProxxi.getY());
        }
    }//GEN-LAST:event_formWindowActivated

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        setAndOrganizeSoons.SetLocationSoons(this, soonTavile.getX(), soonTavile.getY(), soonProxxi.getX(), soonProxxi.getY());
    }//GEN-LAST:event_formComponentResized

    private void buttonOrderEditOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrderEditOrderActionPerformed
        if(buttonOrderEditOrder.getText().equals("SALVAR")){
            JOptionPane.showMessageDialog(null, "PEDIDO SALVO COM SUCESSO");
            CallOrderScreen callOrderScreen = new CallOrderScreen();
            this.dispose();
            callOrderScreen.callScreen();
        }
        else{
            CallOrderEdit callOrderEdit = new CallOrderEdit();
            this.dispose();
            callOrderEdit.callScreen();
        }
    }//GEN-LAST:event_buttonOrderEditOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderEditOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderEditOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderEditOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderEditOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderEditOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddNewOrder;
    private javax.swing.JButton buttonLocaleOrder;
    public static javax.swing.JButton buttonOrderEditOrder;
    private javax.swing.JButton buttonRemoverOrder;
    private javax.swing.JFormattedTextField inputCodeOrder;
    private javax.swing.JTextField inputCodePart;
    private javax.swing.JSpinner inputQuantityRequested;
    private javax.swing.JComboBox<String> inputRequestingBranch;
    private javax.swing.JComboBox<String> inputSupplierBranch;
    public static javax.swing.JLabel soonProxxi;
    public static javax.swing.JLabel soonTavile;
    private javax.swing.JScrollPane tableOfOrders;
    private javax.swing.JTable tablePartsOfOrder;
    private javax.swing.JLabel txtCodeOrder;
    private javax.swing.JLabel txtCodePart;
    public static javax.swing.JLabel txtOrderEditOrder;
    private javax.swing.JLabel txtQuantityRequested;
    private javax.swing.JLabel txtRequestingBranch;
    private javax.swing.JLabel txtSupplierBranch;
    // End of variables declaration//GEN-END:variables
}
